#!/usr/bin/env python3
"""Bake the game's two fonts (DejaVu Sans Mono 11 and Bold 13, the sizes the
PC port uses) into font_data.h as 1-bit glyphs, so the handheld build needs
no SDL_ttf or FreeType.

    python3 make_font.py     # writes font_data.h next to this file

DejaVu fonts are free to share (Bitstream Vera licence); keep their notice
(DejaVu-LICENSE.txt) in the package.
"""
import pathlib
import sys

from PIL import Image, ImageDraw, ImageFont

HERE = pathlib.Path(__file__).resolve().parent
DIRS = ["/usr/share/fonts/truetype/dejavu", "/usr/share/fonts/TTF", "/usr/share/fonts/dejavu"]
FONTS = [("mono12", "DejaVuSansMono.ttf", 11), ("bold14", "DejaVuSansMono-Bold.ttf", 13)]


def find(name):
    for d in DIRS:
        p = pathlib.Path(d) / name
        if p.exists():
            return str(p)
    sys.exit("missing " + name + " (apt install fonts-dejavu-core)")


def bake(name, file, size):
    font = ImageFont.truetype(find(file), size)
    ascent, descent = font.getmetrics()
    w = int(round(font.getlength("M")))
    h = ascent + descent
    assert w <= 16
    glyphs = []
    for code in range(32, 127):
        img = Image.new("L", (w + 4, h + 4), 0)
        d = ImageDraw.Draw(img)
        d.fontmode = "1"
        d.text((0, ascent), chr(code), font=font, fill=255, anchor="ls")
        rows = []
        for y in range(h):
            bits = 0
            for x in range(w):
                if img.getpixel((x, y)) > 127:
                    bits |= 1 << x
            rows.append(bits)
        glyphs.append(rows)
    out = ["static const int FONT_%s_W = %d, FONT_%s_H = %d, FONT_%s_ASCENT = %d;" % (
        name, w, name, h, name, ascent),
        "static const unsigned short FONT_%s[95][%d] = {" % (name, h)]
    for code, rows in zip(range(32, 127), glyphs):
        out.append("    {%s}, /* %s */" % (",".join("0x%04x" % r for r in rows),
                                            chr(code).replace("\\", "bs").replace("*", "star").replace("/", "slash")))
    out.append("};")
    print("%s: %dx%d, ascent %d" % (name, w, h, ascent))
    return out


def main():
    lines = ["/* GENERATED by make_font.py - do not edit. 1-bit glyphs for ASCII 32..126:",
             "   one unsigned short per row, bit x = column x. */"]
    for spec in FONTS:
        lines += bake(*spec)
    (HERE / "font_data.h").write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
