#!/usr/bin/env python3
"""Bundle src/*.lua into the single churn.lua that runs on SolarOS.

The game is edited as small files in src/ and shipped as one script (SolarOS
Lua has no `require` for user files, and one file is easy to copy to the
device). The parts are concatenated in file-name order and share one scope:
a local defined in 10_sprites.lua is visible in every later part, exactly as
if it were one file - they are chapters, not modules.

    python3 tools/build.py          # write churn.lua
    python3 tools/build.py --check  # exit 1 if churn.lua is out of date

Never edit churn.lua by hand; edit src/ and rebuild.
"""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
OUT = ROOT / "churn.lua"

BANNER = (
    "-- GENERATED by tools/build.py from src/*.lua - do not edit this file;\n"
    "-- edit the parts in src/ and run: python3 tools/build.py\n"
)


def bundle():
    parts = sorted(SRC.glob("*.lua"))
    if not parts:
        sys.exit("no parts in " + str(SRC))
    out = [BANNER]
    for part in parts:
        text = part.read_text()
        if not text.endswith("\n"):
            text += "\n"
        out.append(text)
    return "".join(out), parts


def main():
    text, parts = bundle()
    if "--check" in sys.argv:
        current = OUT.read_text() if OUT.exists() else ""
        if current != text:
            sys.exit("churn.lua is out of date: run python3 tools/build.py")
        print("churn.lua is up to date (%d parts)" % len(parts))
        return
    OUT.write_text(text)
    print("built %s from %d parts, %d lines" % (OUT.name, len(parts), text.count("\n")))


if __name__ == "__main__":
    main()
