#!/usr/bin/env python3
"""Bundle src/*.lua into the single churn.lua that runs on SolarOS.

The game is edited as small files in src/ and shipped as one script (SolarOS
Lua has no `require` for user files, and one file is easy to copy to the
device). The parts are concatenated in file-name order and share one scope:
a local defined in 10_sprites.lua is visible in every later part, exactly as
if it were one file - they are chapters, not modules.

    python3 tools/build.py          # write churn.lua
    python3 tools/build.py --check  # exit 1 if churn.lua is out of date

Never edit churn.lua by hand; edit src/ and rebuild.

Version: tools/version.json holds {"series", "build", "date", "digest"}. When
the parts change (their digest differs), the build number is the last
commit's + 1 and the date is today's (rebuilding before a commit never
counts twice); the same parts rebuild to the same file. The version
("0.13.7 (2026-10-05)") is the first line of churn.lua and replaces
"@VERSION@" in the parts (Game.VERSION, shown on the H/V info page).
"""
import datetime
import hashlib
import json
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
OUT = ROOT / "churn.lua"
VERSION_FILE = ROOT / "tools" / "version.json"

BANNER = (
    "-- GENERATED by tools/build.py from src/*.lua - do not edit this file;\n"
    "-- edit the parts in src/ and run: python3 tools/build.py\n"
)


def bundle():
    parts = sorted(SRC.glob("*.lua"))
    if not parts:
        sys.exit("no parts in " + str(SRC))
    out = [BANNER]
    for part in parts:
        text = part.read_text()
        if not text.endswith("\n"):
            text += "\n"
        out.append(text)
    return "".join(out), parts


def committed_version():
    """tools/version.json as the last commit has it (None outside git): new
    builds count from there, so a commit is one step however often you
    rebuilt before it."""
    try:
        out = subprocess.run(["git", "show", "HEAD:./tools/version.json"], cwd=ROOT,
                             capture_output=True, text=True, check=True).stdout
        return json.loads(out)
    except (OSError, subprocess.CalledProcessError, ValueError):
        return None


def version(body, bump):
    """The version for these parts: the committed one while they're the
    same, else the committed build + 1 (saved, unless only checking)."""
    v = json.loads(VERSION_FILE.read_text())
    digest = hashlib.sha256(body.encode()).hexdigest()[:16]
    if digest != v["digest"] and bump:
        base = committed_version() or v
        if digest == base["digest"]:
            v = base
        else:
            v = dict(base, build=base["build"] + 1, digest=digest,
                     date=datetime.date.today().isoformat())
        VERSION_FILE.write_text(json.dumps(v, indent=2) + "\n")
        print("version %s.%d" % (v["series"], v["build"]))
    return "%s.%d (%s)" % (v["series"], v["build"], v["date"])


def main():
    body, parts = bundle()
    ver = version(body, "--check" not in sys.argv)
    text = "-- The Churn version " + ver + "\n" + body.replace('"@VERSION@"', '"%s"' % ver)
    if "--check" in sys.argv:
        current = OUT.read_text() if OUT.exists() else ""
        if current != text:
            sys.exit("churn.lua is out of date: run python3 tools/build.py")
        print("churn.lua is up to date (%d parts)" % len(parts))
        return
    OUT.write_text(text)
    print("built %s from %d parts, %d lines" % (OUT.name, len(parts), text.count("\n")))


if __name__ == "__main__":
    main()
