#!/usr/bin/env python3
"""Bake the title screens' pictures (the user's own) into the GENERATED part
src/69_title_art.lua.

    python3 tools/paint_title.py      # then: python3 tools/build.py

  art/splash.png -> Game.SPLASH_ART   the start screen (the splash on launch)
  art/title.png  -> Game.TITLE_ART    the title menu

Each picture is 2:3; it becomes 192x288 (6x9 tiles of 32x32, so no tile runs
off the 300-px screen), ordered-dithered to 1-bit like the portraits, and is
stored as raw bytes (src/68_intro.lua draws it). Previews go to
previews/<name>_art.png (gray) and previews/<name>_art_1bit.png.
"""
import pathlib
import sys

import numpy as np
from PIL import Image, ImageOps

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from paint_portraits import dither, pack_tiles  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "69_title_art.lua"
W, H = 192, 288
# name, source, Lua field, inset (fraction cropped off every side: the
# splash has worn, speckled edges), and dither()'s lo/hi stretch and gamma
PICTURES = [
    ("splash", "splash.png", "SPLASH_ART", 0.06, (0.15, 0.75, 0.6)),
    ("title", "title.png", "TITLE_ART", 0.0, (0.04, 0.92, 0.85)),
]


def lua_bytes(data):
    """A Lua string literal holding these raw bytes (printable ASCII as is,
    the rest as \\ddd): a quarter smaller in memory than base64, and no
    decoding at run time."""
    out = []
    for b in data:
        if 32 <= b < 127 and b not in (34, 92):
            out.append(chr(b))
        else:
            out.append("\\%03d" % b)
    return '"' + "".join(out) + '"'


def bake(name, source, inset, tone):
    img = Image.open(ROOT / "art" / source).convert("L")
    if inset:
        w, h = img.size
        dx, dy = int(w * inset), int(h * inset)
        img = img.crop((dx, dy, w - dx, h - dy))
    img = ImageOps.fit(img, (W, H), Image.LANCZOS, centering=(0.5, 0.5))
    lo, hi, gamma = tone
    bits = dither(img, lo=lo, hi=hi, gamma=gamma)
    data, tw, th = pack_tiles(bits)
    assert (tw, th) == (W // 32, H // 32)
    prev = ROOT / "previews"
    img.save(prev / ("%s_art.png" % name))
    Image.fromarray(np.uint8(~bits) * 255, "L").save(prev / ("%s_art_1bit.png" % name))
    print("%s: %d bytes, %d%% ink" % (source, len(data), int(bits.mean() * 100)))
    return lua_bytes(data), tw, th


def main():
    lines = ["-- GENERATED by tools/paint_title.py from art/splash.png and art/title.png -",
             "-- do not edit. The title screens' pictures: %dx%d, 1-bit, tiles of 32x32" % (W, H),
             "-- (128 bytes each, row-major, LSB = leftmost pixel), as raw bytes."]
    for name, source, field, inset, tone in PICTURES:
        lit, tw, th = bake(name, source, inset, tone)
        lines += ["Game.%s = {w = %d, h = %d, tw = %d, th = %d," % (field, W, H, tw, th),
                  "    data = %s}" % lit]
    OUT.write_text("\n".join(lines) + "\n")
    print("wrote", OUT.name)


if __name__ == "__main__":
    main()
