#!/usr/bin/env python3
"""Bake art/title.png (the user's picture for the title screens) into the
GENERATED part src/69_title_art.lua.

    python3 tools/paint_title.py      # then: python3 tools/build.py

The picture is 2:3; it becomes 192x288 (6x9 tiles of 32x32, so no tile runs
off the 300-px screen), ordered-dithered to 1-bit like the portraits, and
stored base64 in Game.TITLE_ART (src/68_intro.lua draws it).
Previews go to previews/title_art.png (gray) and previews/title_art_1bit.png.
"""
import base64
import pathlib
import sys

import numpy as np
from PIL import Image, ImageOps

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from paint_portraits import dither, pack_tiles  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "art" / "title.png"
OUT = ROOT / "src" / "69_title_art.lua"
W, H = 192, 288
# tone: lo/hi stretch and gamma for dither(); the picture is mostly dark, so
# lift the mid-tones a little to keep the cloud bands and the figure apart
LO, HI, GAMMA = 0.04, 0.92, 0.85


def main():
    img = Image.open(SRC).convert("L")
    img = ImageOps.fit(img, (W, H), Image.LANCZOS, centering=(0.5, 0.5))
    bits = dither(img, lo=LO, hi=HI, gamma=GAMMA)
    data, tw, th = pack_tiles(bits)
    assert (tw, th) == (W // 32, H // 32)
    b64 = base64.b64encode(data).decode()
    lines = ["-- GENERATED by tools/paint_title.py from art/title.png - do not edit.",
             "-- The title screens' picture: %dx%d, 1-bit, %dx%d tiles of 32x32" % (W, H, tw, th),
             "-- (128 bytes each, row-major, LSB = leftmost pixel), base64.",
             "Game.TITLE_ART = {w = %d, h = %d, tw = %d, th = %d," % (W, H, tw, th),
             "    data = \"%s\"}" % b64, ""]
    OUT.write_text("\n".join(lines))
    prev = ROOT / "previews"
    img.save(prev / "title_art.png")
    Image.fromarray(np.uint8(~bits) * 255, "L").save(prev / "title_art_1bit.png")
    print("wrote %s (%d bytes base64, %d%% ink)" % (OUT.name, len(b64), int(bits.mean() * 100)))


if __name__ == "__main__":
    main()
